### ISSUE TITLE
Make sure OLAC metainfo is in the corpus pages header for SEO

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#1327]
"accessible via normal search mechanisms (e.g. Google, or the Open Archives Initiative (OAI)11). Non-compliant repositories – those whose catalogs do not conform to the normal standards (e.g., OLAC) of our research community – should be encouraged to conform. The benefit of conforming is that federated searches will include these repositories and we will thus begin, as a community of researchers, to create a dynamic documentation index of archived information about the world’s languages, as provided by OLAC, and then harvested by any similar project (e.g. the Clarin Virtual Language Observatory12 or ELCat13). " Thieberger:2012

**Comment by HughP** [comment]
Just a quick question: SEO is a two way street. I mean I don't think googlebot is going to know what to do with OLAC info in a page header. I am under the impression that their search ranking algorithm does not even know what DCMI is, (or [meta keywords](http://blog.woorank.com/2013/04/dublin-core-metadata-for-seo-and-usability/)) ... not to say that it is not, a good place for it. Conversely though googlebot might think the header is being trashed up.... So is this issue suggesting that this project's SEO strategy is targeting a bot which crawls looking for OLAC data in headers which is not Googlebot? (If so that is awesome!) I was under the impression that OLAC metadata has to be pushed to OLAC as an XML file, therefore that was the only SEO benefit from the metadata; find-ability via the OLAC website.
