### ISSUE TITLE
Create an FAQ for instructors

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#1614]
For now this is some things I can think of:

When to use LingSync:
So far it seems like classes often register sometime in the first month, and the instructor creates one DB and then adds the students to it (once they have registered). Most groups won't need the database until after they are done with the phonemic inventory. I think all instructors required students to input data from their extra elicitation sessions with the consultant. (Each elicitation session in real life corresponded pretty much with an elicitation session in the app).

Custom data entry: 
Half of the instructors requested custom data entry templates for their corpus (usually sometime in the middle of the semester after the phonemic inventory is done etc), the just drew what they wanted data entry to look like on paper and we put it in the app.

Audio:
Some classes used an iPad or something like that to record unique utterances into the app during class time, I'm not sure how they did it (I would have recorded the entire session instead). This summer we added Long Audio import so you can record entire elicitation sessions and have it automatically detect utterances (details are in this video http://youtu.be/IcsdPyYEMFc) 

Word Lists:
Some instructors wanted wordlists for students so we added buttons for this in the Prototype app, and links in the Spreadsheet app (in the FAQ export section).

Most recently commented datum:
Some instructors wanted to see which datum were commented most, or most recently since students might be asking questions in the comments or discussing good things like reaching a consensus about a form. We added a view for this but I have to fish around for the instructions on how to use it. 

Exporting data by elicitation session:
Some instructors were creating lists of data per elicitation session using the Prototype and using the LaTeX button to create a pdf (we had another request recently so we made video http://youtu.be/e1RzexNSie4)

**Comment by louisa-bielig** [comment]
<h1 class="">FAQ for Instructors</h1>

<div class="question " >When should my students start using LingSync?</div>
<div class="answer " >You as the instructor will ideally register and create a database by the beginning of the class, so that your students can register within the first few weeks. You can make a new account by going to the <a href="http://app.lingsync.org"> LingSync app</a>, and create a corpus by logging in, hovering over 'Settings', and selecting 'Corpus', where you will have the option of creating a new corpus. Once your students have registered, you can add them to your database by going to the "Admin" features .This way, they will have signed up and familiarized themselves with the database by the time you have discussed phonetics and the phonemic inventory.</div>

<div class="answer " >Before you let students start entering data into your corpus, it may be helpful to provide them with glossing conventions (e.g. the Leipzig glossing rules). While they will certainly gloss some lexical entries incorrectly in the beginning, it will facilitate the searching process, and therefore ultimately the cleaning process, of glosses in your data. </div>


<div class="question " >What constitues an elicitation sessions?</div>
<div class="answer " >Each elicitation session in real life usually corresponds to an elicitation session in the app. If students have their own elicitation sessions outside of the classroom, it may also be helpful for them to enter their name (and potentially the date of elicitation) alongside the elicitation goal, so that they can easily find their own sessions to be cleaned. This will also facilitate the evaluation of progress for individual students. </div>


<div class="question " >What should students do if they find mistakes in their own or other students' data?</div>
<div class="answer " >When students find mistakes in their own data and are confident about fixing them, they may directly edit the data in question, which will generate a record of the change on the right of each edited datum below the "Edit" button. However, if students find mistakes in other students' data, it is recommended that they comment on the relevant data, rather than changing it themselves. This way, students can discuss differences in their glosses without irreversably changing data, since once data has been changed, the LingSync team has to be contacted to change them back to an earlier version. A video on how to create comments under a datum in lingsync can be found <a href="https://www.youtube.com/watch?v=U6fvGxm7LoU"> here</a>.</div>
  

<div class="question " >Custom data entry?</div>
<div class="answer " > </div>


<div class="question " >Audio?</div>
<div class="answer " > </div>


<div class="question " >Word Lists?</div>
<div class="answer " > </div>


<div class="question " >Most recently commented datum?</div>
<div class="answer " > </div>


<div class="question " >Exporting data by elicitation session?</div>
<div class="answer " > </div>

**Comment by cesine** [comment]
@louisa-bielig we have to remember to connect this to the FAQ tomorrow, since your machine is the only one which is set up to edit the spreadsheet app.
