### ISSUE TITLE
JSON export via Spreadsheet has no "date entered"

### ISSUE THREAD

**Issue by jrwdunham** [FieldDB/FieldDB#2068]
This field should be present in the export, should it not? If a user wants to post-process their export file so that it is displayed in the order that Spreadsheet displays it (which is, I think, by date entered), then this field needs to be present.

**Comment by cesine** [comment]
If you are working on export, you should be using the export `extract_and_transform` map reduces, not the old `pages` ones:
https://github.com/FieldDB/LinguisticDataConverters/tree/master/views

You couldn't know this because you don't have them in your databases. We couldn't release them until the spreadsheet was released (waiting from march 31st to aug 1st). You can use them by replicating the `new_export` database into your databases. We can replicate them to all the testing dbs if you want? Although if you're still using "jrwdunham"  for your development then this wont help you.

----- 

I agree this is a pretty big oversight in the `get_datum_fields` export! that json `get_datum_fields` was just fields by definition, i think that map reduces was created for search and reused ever since for random reasons so its completely lacking design. " so if we want it to be useful, we should add more stuff to its successor `data_by_creation_date_as_flat_object`

you could add this in 
https://github.com/FieldDB/LinguisticDataConverters/blob/master/views/data_by_creation_date_as_flat_object/map.js#L59

`obj.dateCreated = dateEntered;`
`obj.dateModified = doc.dateModified;`

None of the map reduces have been updated to 3.x yet since we hadn't released the spreadsheet yet there was very little data created using 3.x until you start using in dative. 

If you choose to fix this issue, you should also update the dateEntered to come from dateCreated if its 3.x because if it was saved using v3.x it knows how to find all the old dates for date created and put it  into dateCreated

https://github.com/FieldDB/LinguisticDataConverters/blob/master/views/data_by_creation_date_as_flat_object/map.js#L45
 var dateEntered = doc.dateCreated || doc.dateEntered;
