### ISSUE TITLE
FieldDB API overwrites _.bind (line 51552 of fielddb.js); raises TypeError

### ISSUE THREAD

**Issue by jrwdunham** [FieldDB/FieldDB#2090]
@cesine Is it necessary that the FieldDB API overwrite _.bind ? This seems to be causing issues. See screenshots.

Can you rename this or do you have a solution on my end?

<img width="458" alt="screen shot 2015-09-24 at 9 45 30 pm" src="https://cloud.githubusercontent.com/assets/2504271/10093349/1b7b3bce-6306-11e5-83e0-300a43293814.png">
<img width="671" alt="screen shot 2015-09-24 at 9 46 06 pm" src="https://cloud.githubusercontent.com/assets/2504271/10093350/1b7fe7dc-6306-11e5-8ed8-fd80190c1301.png">
<img width="714" alt="screen shot 2015-09-24 at 9 46 24 pm" src="https://cloud.githubusercontent.com/assets/2504271/10093351/1b83d068-6306-11e5-812b-bf87a7d2070d.png">

**Comment by cesine** [comment]
its probably the frb library... i'll take a look :(

**Comment by cesine** [comment]
@jrwdunham i removed the dependancy since  e only used underscore in some sections of the code that came from the backbone app.  

I don't get the same error that you mentioned when I run dative (basically all i can do is log in because my other pull requests involving map reduces havent been accepted so i cant load a corpus or a form) on my machine, i'm guessing it should show anytime backbone tries to bind so maybe i've successfully reproduced it :)

Are you able to checkout the branch `cesine:fix/bindoverwrite` and build, or how can you test to see if this fixes it before we go ahead and merge this...

**Comment by jrwdunham** [comment]
@cesine thanks for merging this. I don't know how to recreate the `_.bind` bug. It occurred sporadically. But if you use Dative for any length of time you would have seen it cropping up.
