### ISSUE TITLE
Update website with info for how to use dative

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#2101]
next semester we will recommend all classes use dative instead of the spreadsheet app. @hisakonog here is an issue to track the site updates :) i forgot to tell you to pull from upstream before you make the changes

**Comment by cesine** [comment]
Thanks so much for taking the time to send this to us! Its important to us to hear both the good and the frustrating. We have created an issue #2095 and noted the known solutions to the student's problems, and added TODOs for the ones that we think are bugs. 

Do you know why none of the students used the "Contact Us" button during the semester? It would have been much less frustrating for them to not feel like they were plodding away in the dark. We usually send out a welcome email to instructors with additional info and instructions  for customizing the corpus but we didn't hear that you were using the app so we didn't include you in the instructors email. I will forward you a copy now although its a bit too late.

**Comment by hisakonog** [comment]
Website changes proposed by Alan: 

Tutorial>>Spreadsheet Tutorial" link from menu bar: Currently links to Tobin's slides. This should be altered so that it first goes to a page that says:
"LingSync Spreadsheet is no longer supported. It will soon be replaced by Dative. Due to this, we have modified Spreadsheet.
* users can no longer create new accounts
* users can no longer create new corpora 

The steps to create new corpora and new users in the tutorial no longer apply. If you already have an account and corpora on spreadsheet, you will still have access to this data. We are not planning to shut Spreadsheet down; however we will no longer be fixing its bugs."
AS HYPERLINK: Proceed to tutorial.

"Apps>>Spreadsheet" link from menu bar: Currently links to bullet points of Spreadsheet features. Instead, it should link to a page that says:
"LingSync Spreadsheet is being replaced by Dative. As a result, Spreadsheet is no longer supported. Due to this, we have modified Spreadsheet.
* users can no longer create new accounts
* users can no longer create new corpora 

If you already have an account and corpora on Spreadsheet, you will still have access to this data. We are not planning to shut Spreadsheet down; however we will no longer be fixing its bugs.
Dative is currently being beta tested and will be released to the general public soon. We are currently developing methods to migrate from Spreadsheet to Dative. For more information, click here (hyperlinked to Dative website)."

"Go to LingSync Spreadsheet" Link: Currently goes to login. It should first go to a page that says:
"LingSync Spreadsheet is being replaced by Dative. As a result, Spreadsheet is no longer supported. Due to this, we have modified Spreadsheet.
* users can no longer create new accounts
* users can no longer create new corpora 

If you already have an account and corpora on Spreadsheet, you will still have access to this data. We are not planning to shut Spreadsheet down; however we will no longer be fixing its bugs.

To proceed to login, click here (hyperlink to Login page)

For more information about Dative, click here (hyperlinked to Dative website)."

**Comment by hisakonog** [comment]
pull request made on FieldDbWebServer. Modifications does not include "how to use Dative" (which is not ready yet).

**Comment by hisakonog** [comment]
another pull request on FieldDBWebServer. Edited warning page so that it is consistent with the email message users received. Removed Spreadsheet-related links from the warning page; we no longer allow new users, so there is no point letting them to "check out" Spreadsheet.

**Comment by cesine** [comment]
this was done
